name: nightly
on:
  push:
    branches: [main, master]
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    branches: [main, master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.job }}
  cancel-in-progress: true

jobs:
  nightly:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base: [debian, alpine]
    env:
      HEDGEDOC_VERSION: master
      HEDGEDOC_IMAGE: quay.io/hedgedoc/hedgedoc-nightly
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3

      - name: Set date
        run: echo TODAY=$(date +%Y%m%d) >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # tag=v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c # v2

      - name: Login to docker registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # tag=v2
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # v4
        with:
          context: .
          file: ./${{ matrix.base }}/Dockerfile
          labels: quay.expires-after=1w
          cache-from: type=gha
          cache-to: type=gha
          build-args: |
            VERSION=${{ env.HEDGEDOC_VERSION }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ github.event_name == 'push' }}
          tags: |
            ${{ env.HEDGEDOC_IMAGE }}:${{ env.TODAY }}-${{ matrix.base }}
            ${{ env.HEDGEDOC_IMAGE }}:${{ matrix.base }}
