name: nightly
on:
  push:
    branches: [main, master]
  schedule:
    - cron: "0 0 * * *"

jobs:
  nightly:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base: [debian, alpine]
    env:
      HEDGEDOC_VERSION: master
      HEDGEDOC_IMAGE: quay.io/hedgedoc/hedgedoc-nightly
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2

      - name: Set date
        run: echo TODAY=$(date +%Y%m%d) >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480 # renovate: tag=v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25 # renovate: tag=v1

      - name: Login to docker registry
        uses: docker/login-action@bb984efc561711aaa26e433c32c3521176eae55b # tag=v1
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@7f9d37fa544684fb73bfe4835ed7214c255ce02b # renovate: tag=v2
        with:
          context: .
          file: ./${{ matrix.base }}/Dockerfile
          labels: quay.expires-after=1w
          build-args: |
            VERSION=${{ env.HEDGEDOC_VERSION }}
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.HEDGEDOC_IMAGE }}:${{ env.TODAY }}-${{ matrix.base }}
            ${{ env.HEDGEDOC_IMAGE }}:${{ matrix.base }}
