name: Container release
on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base: [debian, alpine]
    env:
      # renovate: datasource=github-tags depName=hedgedoc/hedgedoc versioning=semver
      HEDGEDOC_VERSION: 1.9.8
      HEDGEDOC_IMAGE: quay.io/hedgedoc/hedgedoc
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6a58db7e0d21ca03e6c44877909e80e45217eed2 # v2

      - name: Login to docker registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set flavor tags
        run: echo "TAGS=$HEDGEDOC_IMAGE:${{ env.HEDGEDOC_VERSION }}-${{ matrix.base }},$HEDGEDOC_IMAGE:${{ matrix.base }}" >> $GITHUB_ENV

      - name: Set main flavor tags
        if: ${{ matrix.base == 'debian' }}
        run: echo "TAGS=$TAGS,$HEDGEDOC_IMAGE:${{ env.HEDGEDOC_VERSION }},$HEDGEDOC_IMAGE:latest" >> $GITHUB_ENV

      - name: Build and push image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # v4
        with:
          context: .
          file: ./${{ matrix.base }}/Dockerfile
          build-args: |
            VERSION=${{ env.HEDGEDOC_VERSION }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.TAGS }}
