name: Container release
on:
  push:
    branches: [main, master]

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base: [debian, alpine]
    env:
      # renovate: datasource=github-tags depName=hedgedoc/hedgedoc versioning=semver
      HEDGEDOC_VERSION: 1.9.5
      HEDGEDOC_IMAGE: quay.io/hedgedoc/hedgedoc
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # tag=v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325 # tag=v2

      - name: Login to docker registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # tag=v2
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set flavor tags
        run: echo "TAGS=$HEDGEDOC_IMAGE:${{ env.HEDGEDOC_VERSION }}-${{ matrix.base }},$HEDGEDOC_IMAGE:${{ matrix.base }}" >> $GITHUB_ENV

      - name: Set main flavor tags
        if: ${{ matrix.base == 'debian' }}
        run: echo "TAGS=$TAGS,$HEDGEDOC_IMAGE:${{ env.HEDGEDOC_VERSION }},$HEDGEDOC_IMAGE:latest" >> $GITHUB_ENV

      - name: Build and push image
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5 # tag=v3
        with:
          context: .
          file: ./${{ matrix.base }}/Dockerfile
          build-args: |
            VERSION=${{ env.HEDGEDOC_VERSION }}
          platforms: linux/amd64
          push: true
          tags: ${{ env.TAGS }}
