name: Container release
on:
  push:
    branches: [main, master]

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base: [debian, alpine]
    env:
      # renovate: datasource=github-tags depName=hedgedoc/hedgedoc versioning=semver
      HEDGEDOC_VERSION: 1.9.4
      HEDGEDOC_IMAGE: quay.io/hedgedoc/hedgedoc
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8 # tag=v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6 # tag=v2

      - name: Login to docker registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # tag=v2
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set flavor tags
        run: echo "TAGS=$HEDGEDOC_IMAGE:${{ env.HEDGEDOC_VERSION }}-${{ matrix.base }},$HEDGEDOC_IMAGE:${{ matrix.base }}" >> $GITHUB_ENV

      - name: Set main flavor tags
        if: ${{ matrix.base == 'debian' }}
        run: echo "TAGS=$TAGS,$HEDGEDOC_IMAGE:${{ env.HEDGEDOC_VERSION }},$HEDGEDOC_IMAGE:latest" >> $GITHUB_ENV

      - name: Build and push image
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94 # tag=v3
        with:
          context: .
          file: ./${{ matrix.base }}/Dockerfile
          build-args: |
            VERSION=${{ env.HEDGEDOC_VERSION }}
          platforms: linux/amd64
          push: true
          tags: ${{ env.TAGS }}
