name: Container release
on:
  push:
    branches: [main, master]

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base: [debian, alpine]
    env:
      # renovate: datasource=github-tags depName=hedgedoc/hedgedoc versioning=semver
      HEDGEDOC_VERSION: 1.9.6
      HEDGEDOC_IMAGE: quay.io/hedgedoc/hedgedoc
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # tag=v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f03ac48505955848960e80bbb68046aa35c7b9e7 # v2

      - name: Login to docker registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # tag=v2
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set flavor tags
        run: echo "TAGS=$HEDGEDOC_IMAGE:${{ env.HEDGEDOC_VERSION }}-${{ matrix.base }},$HEDGEDOC_IMAGE:${{ matrix.base }}" >> $GITHUB_ENV

      - name: Set main flavor tags
        if: ${{ matrix.base == 'debian' }}
        run: echo "TAGS=$TAGS,$HEDGEDOC_IMAGE:${{ env.HEDGEDOC_VERSION }},$HEDGEDOC_IMAGE:latest" >> $GITHUB_ENV

      - name: Build and push image
        uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # v3
        with:
          context: .
          file: ./${{ matrix.base }}/Dockerfile
          build-args: |
            VERSION=${{ env.HEDGEDOC_VERSION }}
          platforms: linux/amd64
          push: true
          tags: ${{ env.TAGS }}
